<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>Kem.Service.App</PackageId>
    <Title>Kem Service App</Title>
    <Version>1.0.1</Version>
    <Authors>Hung Nguyen</Authors>
    <Company>Kem Team</Company>
    <PackageProjectUrl>https://github.com/KemLib/KemService</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/KemLib/KemService</RepositoryUrl>
    <AssemblyVersion>1.0.1</AssemblyVersion>
    <FileVersion>1.0.1</FileVersion>
    <Description>Kem Service App</Description>
    <PackAsTool>False</PackAsTool>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Kem.Lib.Core" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Diagnostics.CodeAnalysis" />
  </ItemGroup>

</Project>
